SET EXCLUSIVE ON
PRIVATE AUXNUMERO,AUXNOMBRE,AUXCIVA,AUXCONTABLE,AUXLINEA,AUXPRECIO,AUXINTERNO
SELECT 1
        USE ARTICULO
SELECT 2
        USE AUXARTIC
SELECT 1
GO TOP
DO WHILE .NOT. EOF()
        AUXNUMERO= NUMERO
        AUXNOMBRE = NOMBRE
        AUXCIVA= CIVA
        AUXCONTABLE= CONTABLE
        AUXLINEA= LINEA
        AUXPRECIO= PRECIO
        AUXINTERNO= INTERNO
        SELECT 2
        APPEND BLANK
        REPLACE NUMERO WITH AUXNUMERO, NOMBRE WITH AUXNOMBRE, CIVA WITH AUXCIVA
        REPLACE CONTABLE WITH AUXCONTABLE, LINEA WITH AUXLINEA, PRECIO WITH AUXPRECIO
        REPLACE INTERNO WITH AUXINTERNO
        SELECT 1
        SKIP
ENDDO
CLOSE ALL


