SET EXCLUSIVE ON
PRIVATE AUXNUMERO,AUXNOMBRE,AUXDOMICILIO,AUXLOCALIDAD,AUXTELEFONO,AUXTDOC,AUXCIVA,AUXCUIT,AUXTIPO,AUXSALDO
SELECT 1
        USE DEUDORES
SELECT 2
        USE AUXDEUDO
SELECT 1
GO TOP
DO WHILE .NOT. EOF()
        AUXNUMERO= NUMERO
        AUXNOMBRE = NOMBRE
        AUXDOMICILIO= DOMICILIO
        AUXLOCALIDAD= LOCALIDAD
        AUXTELEFONO= TELEFONO
        AUXTDOC= TDOC
        AUXCIVA= CIVA
        AUXCUIT= CUIT
        AUXTIPO= TIPO
        AUXSALDO= SALDO
        SELECT 2
        APPEND BLANK
        REPLACE NUMERO WITH AUXNUMERO, NOMBRE WITH AUXNOMBRE, DOMICILIO WITH AUXDOMICILIO
        REPLACE LOCALIDAD WITH AUXLOCALIDAD, TELEFONO WITH AUXTELEFONO, TDOC WITH AUXTDOC
        REPLACE CIVA WITH AUXCIVA, CUIT WITH AUXCUIT, TIPO WITH AUXTIPO, SALDO WITH AUXSALDO
        SELECT 1
        SKIP
ENDDO
CLOSE ALL


