SET EXCLUSIVE ON
PRIVATE AUXFECHA,AUXNOMBRE,AUXCIVA,AUXCUIT,AUXCBTE,AUXALIC,AUXEXENTO,AUXGRAVADO,AUXIVA,AUXIVANO,AUXNETO,AUXCLIENTE
SELECT 1
        USE MOVIVA
SELECT 2
        USE AUXMIVA
SELECT 1
GO TOP
DO WHILE .NOT. EOF()
        AUXFECHA= FECHA
        AUXNOMBRE = NOMBRE
        AUXCIVA= CIVA
        AUXCUIT= CUIT
        AUXCBTE= CBTE
        AUXALIC= ALIC
        AUXEXENTO= EXENTO
        AUXGRAVADO= GRAVADO
        AUXIVA= IVA
        AUXIVANO= IVANO
        AUXNETO= NETO
        AUXCLIENTE= CLIENTE
        SELECT 2
        APPEND BLANK
        REPLACE FECHA WITH AUXFECHA, NOMBRE WITH AUXNOMBRE, CIVA WITH AUXCIVA
        REPLACE CUIT WITH AUXCUIT, CBTE WITH AUXCBTE,ALIC WITH AUXALIC, EXENTO WITH AUXEXENTO
        REPLACE GRAVADO WITH AUXGRAVADO, IVA WITH AUXIVA,IVANO WITH AUXIVANO, NETO WITH AUXNETO
        REPLACE CLIENTE WITH AUXCLIENTE
        SELECT 1
        SKIP
ENDDO
CLOSE ALL


