SET EXCLUSIVE ON
PRIVATE AUXNUMERO,AUXFECHA,AUXTMOV,AUXCBTE,AUXVALOR,AUXSALDO
SELECT 1
        USE MPROVEED
SELECT 2
        USE AUXMPRO
SELECT 1
GO TOP
DO WHILE .NOT. EOF()
        AUXNUMERO= NUMERO
        AUXFECHA = FECHA
        AUXTMOV= TMOV
        AUXCBTE= CBTE
        AUXVALOR= VALOR
        AUXSALDO= SALDO
        SELECT 2
        APPEND BLANK
        REPLACE NUMERO WITH AUXNUMERO, FECHA WITH AUXFECHA, TMOV WITH AUXTMOV
        REPLACE CBTE WITH AUXCBTE,VALOR WITH AUXVALOR, SALDO WITH AUXSALDO
        SELECT 1
        SKIP
ENDDO
CLOSE ALL


